### ISSUE TITLE
Can't go past the first page in Mass Edit mode

### ISSUE THREAD

**Issue by Mycheze** [dekkerglen/CubeCobra#1822]
**Describe the bug**
When trying to mass edit my cubes, I am unable to go to the second page or further. It loads, but then immediately goes back to page 1.

**To Reproduce**
1. Enter Mass Edit mode
2. Try to go to second page
3. Get sent back to first page

**Expected behavior**
To be able to view each page in the list

**Screenshots**
Not really a "pictures" thing. If you want, contact me on Discord (Mycheze#3344) and I can send a short video of the issue.

**Desktop (please complete the following information):**
 - OS: Pop!_OS
 - Browser: Firefox
 - Version: 85.0.1

**Smartphone (please complete the following information):**

**Additional context**
Also, if would be really nice to have a navigation bar at the bottom of the mass edit page as well. I always have to scroll to the top once I'm done doing things. That's a small QOL thing though. Thanks for the amazing website!

**Comment by lunakv** [comment]
This issue is already fixed by #1817 and can be closed.

**Comment by Mycheze** [comment]
> This issue is already fixed by #1817 and can be closed.

I'm happy to close it, but I am still experiencing this issue. Is there something I should do on my end to fix it?

**Comment by lunakv** [comment]
You just have to wait until the next release. #1817 isn't running in production yet.

**Comment by Mycheze** [comment]
Sick, thanks.
