### ISSUE TITLE
Can't export deck after draft. Does not affect all cubes.

### ISSUE THREAD

**Issue by awawis** [dekkerglen/CubeCobra#1894]
Every time I draft my cube (latest attempt [here](https://cubecobra.com/cube/deck/deckbuilder/607a451bc3d559199e839692)), I am unable to build a deck afterward.

The page loads and looks like this:
![](https://i.imgur.com/gqNU4Zd.png)

When I [draft other cubes](https://cubecobra.com/cube/deck/deckbuilder/607a457cc3d559199e839caf), I get this screen which lets me build my deck successfully:
![](https://i.imgur.com/W4j7juN.png)

Troubleshooting attempted:
- Reproduced in both Firefox and Edge
- Tried rebooting
- Tried logged in and logged out

Notes about my cube:
- It was originally cloned from [this cube](https://cubecobra.com/cube/list/old_border)
- I feel like I had successful drafts in the past (weeks ago) possibly before I added certain cards?

**Comment by dekkerglen** [comment]
Looks like you're not logged in

**Comment by awawis** [comment]
As I mentioned in my original post, I tried while logged in and while logged out with the same results. Here is my attempt from just now:
![image](https://user-images.githubusercontent.com/22629881/115101733-84631d00-9efb-11eb-9969-5c0042440364.png)

I think the issue would be easily reproducible - it would just require someone to try drafting the cube.

**Comment by dekkerglen** [comment]
Yes this is expected behavior logged out

**Comment by awawis** [comment]
Oh - well, in any case, it's happening while I'm logged in too as seen in the latest screenshot.

**Comment by awawis** [comment]
@dekkerglen When I draft other cubes, even while logged out, I am able to export my drafted cards. With my cube, I don't even get that option. I am able to export when I draft other cubes while logged out, so it's definitely different behavior with mine.

I've tried cloning my cube and the issue persists with the cloned cube. I can repro this 100% of the time with my cube and have not found any other cubes exhibiting this issue so far.

Do you have any suggestions for a workaround?

One thing I have noticed: if I try to drag a card from my pool at all after drafting, the cards all disappear and this text shows up:

```
e.details is undefined

f@https://cubecobra.com/js/CubeDraftPage.bundle.js:2:167413
renderWithHooks@https://unpkg.com/react-dom@16/umd/react-dom.development.js:14938:29
updateFunctionComponent@https://unpkg.com/react-dom@16/umd/react-dom.development.js:17169:22
beginWork@https://unpkg.com/react-dom@16/umd/react-dom.development.js:18745:18
callCallback@https://unpkg.com/react-dom@16/umd/react-dom.development.js:182:16
invokeGuardedCallbackDev@https://unpkg.com/react-dom@16/umd/react-dom.development.js:231:18
invokeGuardedCallback@https://unpkg.com/react-dom@16/umd/react-dom.development.js:286:33
beginWork$1@https://unpkg.com/react-dom@16/umd/react-dom.development.js:23338:30
performUnitOfWork@https://unpkg.com/react-dom@16/umd/react-dom.development.js:22292:14
workLoopSync@https://unpkg.com/react-dom@16/umd/react-dom.development.js:22265:24
performSyncWorkOnRoot@https://unpkg.com/react-dom@16/umd/react-dom.development.js:21891:11
flushSyncCallbackQueueImpl/<@https://unpkg.com/react-dom@16/umd/react-dom.development.js:11224:26
unstable_runWithPriority@https://unpkg.com/react@16/umd/react.development.js:2685:14
runWithPriority$1@https://unpkg.com/react-dom@16/umd/react-dom.development.js:11174:12
flushSyncCallbackQueueImpl@https://unpkg.com/react-dom@16/umd/react-dom.development.js:11219:26
flushSyncCallbackQueue@https://unpkg.com/react-dom@16/umd/react-dom.development.js:11207:5
scheduleUpdateOnFiber@https://unpkg.com/react-dom@16/umd/react-dom.development.js:21334:11
dispatchAction@https://unpkg.com/react-dom@16/umd/react-dom.development.js:15795:19
d/i<@https://cubecobra.com/js/CubeDraftPage.bundle.js:2:249815
subscribeToStateChange/<@https://cubecobra.com/js/CubeDraftPage.bundle.js:2:179934
m@https://cubecobra.com/js/CubeDraftPage.bundle.js:2:173367
getActions/</r[o]<@https://cubecobra.com/js/CubeDraftPage.bundle.js:2:186125
y/this.handleTopDragStart/<@https://cubecobra.com/js/CubeDraftPage.bundle.js:2:1018056
```

**Comment by ruler501** [comment]
@dekkerglen this is likely fixed with the latest release.

**Comment by awawis** [comment]
It's still not working for me, but the behavior has changed. After drafting is finished, it kicks me back to this page with the error in thee screenshot:
![image](https://user-images.githubusercontent.com/22629881/120883627-08985f00-c593-11eb-8af6-254cd00aa85b.png)

**Comment by dekkerglen** [comment]
@awawis can you confirm if this issue is fixed now? I can't replicate

**Comment by awawis** [comment]
@dekkerglen thanks for checking. I am still seeing the same issue. I've now tried on my phone as well using both Safari and Firefox and even made sure to test over LTE in case there was some local network issue on my end.

Since you couldn't repro, I thought maybe the issue was tied to my account, so I made a new account and tested but got the same result as above: `Cannot read property 'push' of undefined`

Anything else I can try on my end? One test draft randomly worked about a week ago. I didn't do anything differently as far as I know. That draft is here: https://cubecobra.com/cube/deck/60c7d7d7308c9e1020cf38c3

**Comment by awawis** [comment]
Update: I was able to draft successfully 2 out of 5 times yesterday. It seems like it works properly only _sometimes_ if I draft slowly and, oddly, only if I have clicked "Toggle Bot Breakdown".

I can't get it to consistently work, and the Toggle Bot Breakdown may be unrelated, but it worked 2/3 times when I did that and drated slowly, and it worked 0/2 times when I drafted quickly or slowly without toggling the breakdown.

**Comment by awawis** [comment]
Seems to be working about 50% of the time now, but I can't see a pattern. I have a friend who has drafted several times in the last week with a similar success rate.

**Comment by awawis** [comment]
This appears to be resolved; my friends and I have done 15+ drafts without issue this week.

**Comment by Thethifuthus** [comment]
Hi,

I'm getting this error in my cube - happens to be the one from which this cube was cloned. My cube has been undraftable for quite a while now - it's fine for the picking process, but you are unable to enter deckbuilding.


Error message when moving to deck-building is always
`Cannot read property 'push' of undefined

Cube link: [old_border](https://cubecobra.com/cube/playtest/old_border)

**Comment by awawis** [comment]
I was able to repro the issue with @Thethifuthus' old_border cube.

Perhaps the root cause has to do with a specific card, or settings on a specific card that I copied from their cube, but have since removed or changed from my cube?

**Comment by Thethifuthus** [comment]
> I was able to repro the issue with @Thethifuthus' old_border cube.
> 
> Perhaps the root cause has to do with a specific card, or settings on a specific card that I copied from their cube, but have since removed or changed from my cube?

This is my suspicion too. I have tried removing all the cards that have changed in both of our cubes since this issue surfaced, however I was not able to fix the problem in a cloned copy of my cube. The issue was fixed after replacing about 300-odd cards with copies of frequently cubed cards. I don't want to make changes to my main cube until the culprit is located. 

I have opened a new issue with the details of my testing [here](https://github.com/dekkerglen/CubeCobra/issues/2248). In it, I noted that I suspect the fact that only some of your drafts failed to move to deckbuilding are likely because the offending card(s) were not in the draft pool due to the size of your cube. One way to narrow down the possibilities would be to pool all of the mainboard and sideboard cards of successful drafts while you were experiencing this issue and remove them from the list of possible offenders. However doing this through the front-end of cubecobra doesn't sound too fun!

**Comment by awawis** [comment]
@Thethifuthus here is the list of cards that are currently in your cube that were removed from my cube in the ~2 months before it started working for me (I'm not sure exactly when it started working 100% for me). Maybe you can remove these and see if it works, then narrow from there?

Benevolent Bodyguard
Tireless Tribe
Prismatic Strands
Diabolic Servitude
Warbreak Trumpeter
Chain of Plasma
Arcane Teachings
Grizzly Fate
Roar of the Wurm
Wild Growth
Prophetic Bolt
Goblin Trenches
